// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SistemaContabil.Infrastructure.Data;

#nullable disable

namespace SistemaContabil.Infrastructure.Migrations
{
    [DbContext(typeof(SistemaContabilDb))]
    [Migration("20260524224633_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_cliente");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Conta", b =>
                {
                    b.Property<int>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_conta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConta"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("cliente_id_cliente");

                    b.Property<string>("NomeConta")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("NVARCHAR2(70)")
                        .HasColumnName("nome_conta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("tipo_conta");

                    b.HasKey("IdConta");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("conta_contabil");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_item");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("produto_id_prod");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("quant");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_unit");

                    b.Property<int>("VendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("vendas_id_vendas");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("item_venda");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Marketplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_market");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_market");

                    b.Property<decimal>("ValorComissao")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_comissao");

                    b.HasKey("Id");

                    b.ToTable("marketplace");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pag");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_pag");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("metodo_pag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Taxa")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("taxa_pag");

                    b.HasKey("Id");

                    b.ToTable("pagamento");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_prod");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)")
                        .HasColumnName("descr");

                    b.Property<int>("Estoque")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("estoque");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_prod");

                    b.Property<decimal>("Preco")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.RegistroContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_reg_cont");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CentroCustoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ContaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("conta_contabil_id_conta");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_lanca");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("reg_cont");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vendas");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("cliente_id_cliente");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_venda");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("marketplace_id_market");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("pagamento_id_pag");

                    b.Property<int>("RegContId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("reg_cont_id_reg_cont");

                    b.Property<int>("RegistroContabilId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("status_venda");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_bruto");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_frete");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_liquido");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MarketplaceId");

                    b.HasIndex("PagamentoId");

                    b.HasIndex("RegContId");

                    b.HasIndex("RegistroContabilId");

                    b.ToTable("vendas");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Conta", b =>
                {
                    b.HasOne("SistemaContabil.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("SistemaContabil.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaContabil.Domain.Entities.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.RegistroContabil", b =>
                {
                    b.HasOne("SistemaContabil.Domain.Entities.Conta", "Conta")
                        .WithMany("RegistrosContabeis")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Venda", b =>
                {
                    b.HasOne("SistemaContabil.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaContabil.Domain.Entities.Marketplace", "Marketplace")
                        .WithMany()
                        .HasForeignKey("MarketplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaContabil.Domain.Entities.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.HasOne("SistemaContabil.Domain.Entities.RegistroContabil", "RegCont")
                        .WithMany()
                        .HasForeignKey("RegContId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaContabil.Domain.Entities.RegistroContabil", "RegistroContabil")
                        .WithMany()
                        .HasForeignKey("RegistroContabilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Marketplace");

                    b.Navigation("Pagamento");

                    b.Navigation("RegCont");

                    b.Navigation("RegistroContabil");
                });

            modelBuilder.Entity("SistemaContabil.Domain.Entities.Conta", b =>
                {
                    b.Navigation("RegistrosContabeis");
                });
#pragma warning restore 612, 618
        }
    }
}
